---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.userMobileBackend.name }}-{{ .Values.userMobileBackend.secretName }}
  namespace: {{ .Values.userMobileBackend.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: eks-secret-store
    kind: ClusterSecretStore
  target:
    name:  {{ .Values.userMobileBackend.name }}-{{ .Values.userMobileBackend.secretName }}
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.userMobileBackend.awsSecretName }}