apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.userMobileBackend.name }}
  namespace: {{ .Values.userMobileBackend.namespace }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.userMobileBackend.iamRole }}
