---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.userMobileBackend.name }}-{{ .Values.userMobileBackend.secretName }}
  namespace: {{ .Values.userMobileBackend.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: az-store

  target:
    name:  {{ .Values.userMobileBackend.name }}-{{ .Values.userMobileBackend.secretName }}
    creationPolicy: Owner

  data:
  - secretKey: ZOHO_CLIENT_SECRET
    remoteRef:
      key: {{ .Values.userMobileBackend.namespace }}-{{ .Values.userMobileBackend.name }}-zoho-client-secret
  - secretKey: ZOHO_AUTH_CODE
    remoteRef:
      key: {{ .Values.userMobileBackend.namespace }}-{{ .Values.userMobileBackend.name }}-zoho-auth-code
  - secretKey: JWT_LOGIN_SECRET
    remoteRef:
      key: {{ .Values.userMobileBackend.namespace }}-{{ .Values.userMobileBackend.name }}-jwt-login-secret
  - secretKey: VERIFICATION_TOKEN_SECRET
    remoteRef:
      key: {{ .Values.userMobileBackend.namespace }}-{{ .Values.userMobileBackend.name }}-verification-token-secret
  - secretKey: JWT_REFRESH_SECRET
    remoteRef:
      key: {{ .Values.userMobileBackend.namespace }}-{{ .Values.userMobileBackend.name }}-jwt-refresh-secret
  - secretKey: MAIL_PASSWORD
    remoteRef:
      key: {{ .Values.userMobileBackend.namespace }}-{{ .Values.userMobileBackend.name }}-mail-password
  - secretKey: ZOHO_REFRESH_TOKEN
    remoteRef:
      key: {{ .Values.userMobileBackend.namespace }}-{{ .Values.userMobileBackend.name }}-zoho-refresh-token
  - secretKey: VONAGE_SMS_API_KEY
    remoteRef:
      key: {{ .Values.userMobileBackend.namespace }}-{{ .Values.userMobileBackend.name }}-vonage-sms-api-key
  - secretKey: VONAGE_SMS_API_SECRET
    remoteRef:
      key: {{ .Values.userMobileBackend.namespace }}-{{ .Values.userMobileBackend.name }}-vonage-sms-api-secret
  - secretKey: USER_MOBILE_BACKEND_TOKEN
    remoteRef:
      key: {{ .Values.userMobileBackend.namespace }}-{{ .Values.userMobileBackend.name }}-user-mobile-backend-token
  - secretKey: CASTLE_API_SECRET
    remoteRef:
      key: {{ .Values.userMobileBackend.namespace }}-{{ .Values.userMobileBackend.name }}-castle-api-secret
  - secretKey: APPLE_PRIVATE_KEY
    remoteRef:
      key: {{ .Values.userMobileBackend.namespace }}-{{ .Values.userMobileBackend.name }}-apple-private-key
  - secretKey: APPLE_KEY_ID
    remoteRef:
      key: {{ .Values.userMobileBackend.namespace }}-{{ .Values.userMobileBackend.name }}-apple-key-id
  - secretKey: APPLE_TEAM_ID
    remoteRef:
      key: {{ .Values.userMobileBackend.namespace }}-{{ .Values.userMobileBackend.name }}-apple-team-id
  - secretKey: SENTRY_DSN
    remoteRef:
      key: sentry-dsn-nodejs-backend
  - secretKey: SUMSUB_TOKEN
    remoteRef:
      key: {{ .Values.userMobileBackend.namespace }}-{{ .Values.userMobileBackend.name }}-sumsub-token
  - secretKey: SUMSUB_SECRET_KEY
    remoteRef:
      key: {{ .Values.userMobileBackend.namespace }}-{{ .Values.userMobileBackend.name }}-sumsub-secret-key