apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.userMobileBackend.name }}
  namespace: {{ .Values.userMobileBackend.namespace }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.userMobileBackend.serviceAccountClientId }}
    azure.workload.identity/use-binding: "true"
