// SOCKET RELATED

export const SOCKET_NAMESPACES = {
  ROOM: 'room',
  wallet: 'wallet',
  tango: 'tango',
  EVENT: 'event',
  DFS: 'dfs'
}

export const SOCKET_EMITTERS = {
  ROOM_JOINED: SOCKET_NAMESPACES.ROOM + '_joined',
  UPDATE_BALANCE: SOCKET_NAMESPACES.wallet + '_balance_update',
  TANGO_UPDATE_BALANCE: SOCKET_NAMESPACES.tango + '_balance_update',
  GET_BALANCE: SOCKET_NAMESPACES.wallet + '_get_balance',
  LIVE_SCORES_UPDATE: SOCKET_NAMESPACES.EVENT + '_live_scores_update',
  ROOM_JOINED_EVENT: SOCKET_NAMESPACES.EVENT + '_joined',
  // DFS live contest
  DFS_CONTEST_JOINED: SOCKET_NAMESPACES.DFS + '_contest_joined',
  DFS_LEADERBOARD_DELTA: SOCKET_NAMESPACES.DFS + '_leaderboard_delta',
  DFS_LEADERBOARD_FULL: SOCKET_NAMESPACES.DFS + '_leaderboard_full'
}

export const SOCKET_LISTENERS = {
  GET_BALANCE: SOCKET_NAMESPACES.wallet + '_get_balance',
  UPDATE_BALANCE: SOCKET_NAMESPACES.wallet + '_update_balance',
  JOIN_EVENT_ROOM: SOCKET_NAMESPACES.EVENT + '_join_room',
  // DFS live contest
  DFS_JOIN_CONTEST: SOCKET_NAMESPACES.DFS + '_join_contest',
  DFS_LEAVE_CONTEST: SOCKET_NAMESPACES.DFS + '_leave_contest'
}

export const SOCKET_ROOMS = {
  ROOM_JOINED: SOCKET_NAMESPACES.ROOM + '_joined',
  EVENT_ROOM: SOCKET_NAMESPACES.EVENT + '_room'
}

export const WALLET = {
  GET_BALANCE: SOCKET_LISTENERS.GET_BALANCE,
  UPDATE_BALANCE: SOCKET_LISTENERS.UPDATE_BALANCE
}

export const EVENT = {
  JOIN_ROOM: SOCKET_LISTENERS.JOIN_EVENT_ROOM,
  LIVE_SCORES_UPDATE: SOCKET_EMITTERS.LIVE_SCORES_UPDATE,
  ROOM_JOINED_EVENT: SOCKET_EMITTERS.ROOM_JOINED_EVENT
}
